//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhaSachMetMoi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDH
    {
        public int MaDH { get; set; }
        public int MaSach { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<decimal> Gia { get; set; }
        public string TenSach { get; set; }
        public string AnhBia { get; set; }
        public Nullable<decimal> GiaBan { get; set; }
        public Nullable<int> Sale { get; set; }
    
        public virtual DonHang DonHang { get; set; }
        public virtual Sach Sach { get; set; }
    }
}
