//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhaSachMetMoi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sach()
        {
            this.ChiTietDHs = new HashSet<ChiTietDH>();
        }
    
        public int MaSach { get; set; }
        public string TenSach { get; set; }
        public Nullable<decimal> Gia { get; set; }
        public string KichThuoc { get; set; }
        public string MoTa { get; set; }
        public string AnhBia { get; set; }
        public Nullable<int> NamXB { get; set; }
        public Nullable<int> SoLuongTon { get; set; }
        public Nullable<int> MaTL { get; set; }
        public Nullable<int> MaTG { get; set; }
        public Nullable<int> MaNXB { get; set; }
        public Nullable<int> Sale { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDH> ChiTietDHs { get; set; }
        public virtual NXB NXB { get; set; }
        public virtual TG TG { get; set; }
        public virtual TL TL { get; set; }
    }
}
